export const LOAD_USER_ERROR = "LOAD_USER_ERROR";
export const LOAD_USER_START = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const SUBMIT_USER_ERROR = "SUBMIT_USER_ERROR";
export const SUBMIT_USER_START = "SUBMIT_USER_START";
export const SUBMIT_USER_SUCCESS = "SUBMIT_USER_SUCCESS";
