export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const HIDE_COMMENT = "HIDE_COMMENT";
export const SET_CURRENT_PHOTO_ID = "SET_CURRENT_PHOTO_ID";
export const SHOW_COMMENT = "SHOW_COMMENT";

export const SUBMIT_COMMENT_ERROR = "SUBMIT_COMMENT_ERROR";
export const SUBMIT_COMMENT_START = "SUBMIT_COMMENT_START";
export const SUBMIT_COMMENT_SUCCESS = "SUBMIT_COMMENT_SUCCESS";
